name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      # Remove the "Install Dependencies" step if you don't use Composer
      #- name: Install Composer Dependencies
      #  run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run Tests
        run: echo "No tests to run, as composer.json is missing"
      - name: Run PHP Linter (Syntax Check)
        run: find . -type f -name "*.php" -print0 | xargs -0 -n1 php -l
