name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Change to your required PHP version
          extensions: mbstring, intl, pdo, pdo_mysql  # Add any needed PHP extensions
          coverage: none

      - name: Install Composer Dependencies
        run: |
          composer install --no-progress --no-suggest --prefer-dist

      - name: Run Tests
        run: |
          vendor/bin/phpunit --testdox
